name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swarmus/embedded
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # Verify local build
    - name: build-local
      run: |
        mkdir -p build-local
        cd build-local
        cmake ..
        make
    # Run tests
    - name: tests
      run: |
        cd build-local
        ctest -V

    # Check format
    - name: format
      run: |
        cd build-local
        make check-format

    # Generate documentation
    - name: doc
      run: |
        cd build-local
        make doc

    # Verify esp build
    - name: build-esp
      run: |
        . $IDF_PATH/export.sh
        mkdir -p build-esp
        cd build-esp
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/esp-idf/toolchain-esp32.cmake -DTARGET=esp32
        make
        